#cloud-config
# vim: syntax=yaml
#
# ***********************
# 	---- for more examples look at: ------
# ---> https://cloudinit.readthedocs.io/en/latest/topics/examples.html
# ******************************
#
# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided.
#
# Note: Content strings here are truncated for example purposes.
ssh_pwauth: True
chpasswd:
  list: |
     root:password
  expire: False
users:
  - name: user
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    groups: wheel
    ssh_authorized_keys:
      - ${ssh_pub_key}
#  - name: root
#    shell: /bin/bash
#    groups: wheel
#    ssh_authorized_keys:
#      - ${ssh_pub_key}

bootcmd:
# - sudo snap install microk8s --classic --channel=1.31/stable
# - microk8s status --wait-ready
 - sudo ufw allow in on cni0 && sudo ufw allow out on cni0
 - sudo ufw default allow routed
 - sudo usermod -a -G microk8s user
 - newgrp microk8s
