- name: Label Kubernetes Nodes
  hosts: microk8s_HA
  become: true
  vars:
    master_nodes: "{{ groups['microk8s_HA'] }}"
    worker_nodes: "{{ groups['microk8s_WORKERS'] | map('regex_replace', '-terraform$', '') | list }}"

  tasks:
    - name: Label master node
      command: >
        kubectl label node {{ item }} node-role.kubernetes.io/master=master
      loop: "{{ master_nodes }}"
      ignore_errors: true

    - name: Label worker nodes
      command: >
        kubectl label node {{ item }} node-role.kubernetes.io/worker=worker
      loop: "{{ worker_nodes }}"
      ignore_errors: true
