---
- name: Create and Verify Default StorageClass in Kubernetes cluster
  hosts: microk8s_HA
  tasks:

    - name: Create local-path-provisioner StorageClass
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml
      register: create_local_path_provisioner_result
      ignore_errors: true

    - name: Verify local-path-provisioner creation
      ansible.builtin.shell: |
        kubectl -n local-path-storage get pod
        kubectl get StorageClass
      register: check_local_path_provisioner_class
      failed_when: check_local_path_provisioner_class.rc != 0

    - name: Display local-path-provisioner verification output
      ansible.builtin.debug:
        msg: "{{ check_local_path_provisioner_class.stdout }}"

    - name: Make local-path default StorageClass
      ansible.builtin.shell: |
        kubectl patch StorageClass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
      register: make_local_path_default_storage_class
      failed_when: make_local_path_default_storage_class.rc != 0

    - name: Display output of default StorageClass patch
      ansible.builtin.debug:
        msg: "{{ make_local_path_default_storage_class.stdout }}"
