---
- name: Enable GPU addon in MicroK8s
  hosts: "{{ groups['microk8s_HA'][0] }}" # noqa: ignore-errors ansible-lint[undefined-variable]
  become: true
  tasks:
    - name: Add NVIDIA Helm repository
      shell: microk8s helm repo add nvidia https://helm.ngc.nvidia.com/nvidia
      register: helm_repo_add_result
      ignore_errors: true

    - name: Print NVIDIA Helm Repo Add Output
      debug:
        msg: |
          NVIDIA Helm Repo Add Output:
          {{ helm_repo_add_result.stdout | default('No output') }}

          Errors (if any):
          {{ helm_repo_add_result.stderr | default('No errors') }}

    - name: Update NVIDIA Helm repository
      ansible.builtin.shell:
        cmd: |
          microk8s helm repo update nvidia
      register: helm_repo_update_result
      ignore_errors: true

    - name: Print NVIDIA Helm Repo Update Output
      debug:
        msg: |
          NVIDIA Helm Repo Update Output:
          {{ helm_repo_update_result.stdout | default('No output') }}

          Errors (if any):
          {{ helm_repo_update_result.stderr | default('No errors') }}

    - name: Enable GPU addon in MicroK8s
      ansible.builtin.shell:
        cmd: |
          microk8s enable nvidia
      register: gpu_enable_result
      ignore_errors: true

    - name: Print GPU Addon Enablement Output
      debug:
        msg: |
          GPU Addon Enablement Output:
          {{ gpu_enable_result.stdout | default('No output') }}

          Errors (if any):
          {{ gpu_enable_result.stderr | default('No errors') }}

    - name: Wait for NVIDIA operator validator pod to initialize
      ansible.builtin.shell:
        cmd: |
          microk8s kubectl get pod -n gpu-operator-resources -l app=nvidia-operator-validator -o jsonpath="{.items[0].status.phase}"
      register: pod_status
      retries: 20
      delay: 30
      until: pod_status.stdout == "Running"

    - name: Check logs of NVIDIA operator validator
      ansible.builtin.shell:
        cmd: |
          microk8s kubectl logs -n gpu-operator-resources -lapp=nvidia-operator-validator -c nvidia-operator-validator
      register: validator_logs
      ignore_errors: true

    - name: Print NVIDIA Operator Validator Logs
      debug:
        msg: |
          NVIDIA Operator Validator Logs:
          {{ validator_logs.stdout | default('No logs available') }}

          Errors (if any):
          {{ validator_logs.stderr | default('No errors') }}

    - name: Apply CUDA vector add Pod manifest
      ansible.builtin.shell:
        cmd: |
          microk8s kubectl apply -f - <<EOF
          apiVersion: v1
          kind: Pod
          metadata:
            name: cuda-vector-add
          spec:
            restartPolicy: OnFailure
            containers:
              - name: cuda-vector-add
                image: "k8s.gcr.io/cuda-vector-add:v0.1"
                resources:
                  limits:
                    nvidia.com/gpu: 1
          EOF
      register: pod_apply_result
      ignore_errors: true

    - name: Print CUDA Vector Add Pod Application Output
      debug:
        msg: |
          CUDA Vector Add Pod Application Output:
          {{ pod_apply_result.stdout | default('No output') }}

          Errors (if any):
          {{ pod_apply_result.stderr | default('No errors') }}

    - name: Wait for CUDA vector add pod to complete
      ansible.builtin.shell:
        cmd: |
          microk8s kubectl get pod cuda-vector-add -o jsonpath="{.status.phase}"
      register: cuda_pod_status
      retries: 20
      delay: 30
      until: cuda_pod_status.stdout == "Succeeded"

    - name: Check logs of CUDA vector add pod
      ansible.builtin.shell:
        cmd: |
          microk8s kubectl logs cuda-vector-add
      register: cuda_vector_add_logs
      ignore_errors: true

    - name: Print CUDA Vector Add Pod Logs
      debug:
        msg: |
          CUDA Vector Add Logs:
          {{ cuda_vector_add_logs.stdout | default('No logs available') }}

          Errors (if any):
          {{ cuda_vector_add_logs.stderr | default('No errors') }}

    - name: Display GPU info of nodes
      ansible.builtin.shell:
        cmd: |
          kubectl get nodes -o=custom-columns=NAME:.metadata.name,GPUs:.status.capacity.'nvidia\.com/gpu'
      register: gpu_nodes_info
      ignore_errors: true

    - name: Print GPU Info of Nodes
      debug:
        msg: |
          GPU Info of Nodes:
          {{ gpu_nodes_info.stdout | default('No GPU information available') }}

          Errors (if any):
          {{ gpu_nodes_info.stderr | default('No errors') }}
