---
- name: Manage local VMs with virsh
  hosts: localhost
  gather_facts: no
  become: yes
  vars:
    node_action: "start"

  tasks:
    - name: Gather VM names from inventory
      ansible.builtin.set_fact:
        vm_names: "{{ groups['microk8s_WORKERS'] + groups['microk8s_HA'] }}"

    - name: Start VMs using virsh
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          virsh start {{ item }}
      loop: "{{ vm_names }}"
      when: node_action == "start"

    - name: Shutdown VMs using virsh
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          virsh shutdown {{ item }}
      loop: "{{ vm_names }}"
      when: node_action == "shutdown"
