---
- name: Manage local VMs with virsh
  hosts: localhost
  gather_facts: no
  become: yes
  vars:
    action: "start"

  tasks:
    - name: Gather VM names from inventory
      set_fact:
        vm_names: "{{ groups['microk8s_WORKERS'] + groups['microk8s_HA'] }}"

    - name: Start VMs using virsh
      shell: virsh start {{ item }}
      loop: "{{ vm_names }}"
      when: action == "start"

    - name: Shutdown VMs using virsh
      shell: virsh shutdown {{ item }}
      loop: "{{ vm_names }}"
      when: action == "shutdown"
